### ISSUE TITLE
Empty .c files break program

### ISSUE THREAD

**Issue by blaale** [SJShaw/simpatico#5]
See title.

Output of simpatico.py empty.c is:
Parsing ./empty.c...
Traceback (most recent call last):
  File "/home/tutors/uqsshaw4/2310/simpatico/simpatico.py", line 2429, in <module>
    use_output_file)
  File "/home/tutors/uqsshaw4/2310/simpatico/simpatico.py", line 706, in __init__
    self.current_token = self.tokens[self.position]
IndexError: list index out of range

**Comment by SJShaw** [comment]
fixed in commit f69c3369fc3e544d5f72098acafa7d23ae0c2a5d
